3 задание. ddl scripts
vvvkkkggg/chashka-db pull request #1
Opened 2023-12-08 14:48 UTC by koufesser

2023-12-08 19:32 UTC, unicoooorn requested changes

2023-12-08 19:32 UTC, unicoooorn commented on schemas/All.sql
> +CREATE TABLE Coffeeshop (
добавь if not exists

2023-12-08 19:32 UTC, unicoooorn commented on schemas/All.sql
> +CREATE TABLE Coffeeshop (
а где Create Schema?

2023-12-08 19:32 UTC, unicoooorn commented on schemas/All.sql
> +CREATE TABLE "User" (
почему в кавычках?

2023-12-08 19:32 UTC, unicoooorn commented on schemas/All.sql
> +    SHOP_ID SERIAL PRIMARY KEY,
давай действовать согласно стайлгайду мозиллы 
конкретно здесь атрибуты должны быть в снейк кейсе 


https://docs.telemetry.mozilla.org/concepts/sql_style

2023-12-08 19:32 UTC, unicoooorn commented on schemas/All.sql
> +CREATE TABLE Coffeeshop (
с названием базы таблицы тоже снейк кейс

2023-12-08 19:32 UTC, unicoooorn commented on schemas/User_Reward.sql
> +    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
здесь же клэш имен

2023-12-08 19:32 UTC, unicoooorn commented on schemas/Reward.sql
> +    PRICE INTEGER NOT NULL,
давай везде добавим  CONSTRAINT CHK_Table CHECK (Price>=0)
Аналогично с Bonuses и Total Price

2023-12-08 19:32 UTC, unicoooorn commented on schemas/Item_Receipt.sql
> +    PRIMARY KEY (PRODUCT_ID, RECEIPT_ID)
а зачем?

2023-12-08 19:32 UTC, unicoooorn commented on schemas/Owner.sql
> +    EMAIL VARCHAR(255) NOT NULL
если хочешь можешь упороться и регуляркой проверить емейл и телефон

2023-12-08 19:32 UTC, unicoooorn commented on schemas/Owner.sql
> +    EMAIL VARCHAR(255) NOT NULL
будет круто)))

2023-12-08 21:18 UTC, unicoooorn commented on schemas/User.sql
> +CREATE TABLE "User" (
я вообще думаю он под "Таблицы должны быть в своей схеме" имел в виду не разделение на файлы, а как раз Create Scheme в начале скрипта

2023-12-08 21:18 UTC, unicoooorn commented on schemas/All.sql
> +);
давай еще DROP TABLE IF EXISTS добавим, а то че только create)))

2023-12-08 22:02 UTC, a1k0u commented on schemas/All.sql
> +);
плюсую

2023-12-09 11:50 UTC, a1k0u commented on schemas/User.sql
> +CREATE TABLE "User" (
сорри, я не правильно изъяснился в чате
- нужно создать одну схему, вот [видео с индусом](https://www.youtube.com/watch?v=14wuN6ft5ps), в одном файле со всеми таблицами
- назвать его schema.sql и положить в корень
- в README.md создать новый параграф, где будет указана ссылка на файл
- в шапку README.md, то есть навигацию, добавить ссылку на этот параграф

2023-12-09 11:51 UTC, a1k0u commented on schemas/User.sql
> +CREATE TABLE "User" (
- пусть схема называется CHASHKA
- по именованию, пусть все будет в upper case

2023-12-09 11:53 UTC, a1k0u commented on schemas/Reward.sql
> +    PRICE INTEGER NOT NULL,
CONSTRAINT нужно добавить на 10-15 атрибутов и 2 таблицы. Это одно из условий пункта

2023-12-09 11:56 UTC, a1k0u commented on schemas/All.sql
> +    INN VARCHAR(10) NOT NULL,
должен быть констрейт UNIQUE

2023-12-09 11:56 UTC, a1k0u commented on schemas/All.sql
> +    KKT VARCHAR(16) NOT NULL,
KKT тоже уникальный? @unicoooorn

2023-12-09 12:00 UTC, a1k0u commented on schemas/All.sql
> +    TOTAL INTEGER NOT NULL,
Давай везде, где логично ограничение >= 0 будет стоять CHECK

2023-12-09 12:05 UTC, a1k0u commented on schemas/All.sql
> +    TIMESTAMP TIMESTAMP NOT NULL
-> `timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`

насчет именования даты нужно подумать, т.к. timestamp - ключевое слово в sql

2023-12-09 12:06 UTC, a1k0u commented on schemas/All.sql
> +    TIMESTAMP TIMESTAMP NOT NULL
давайте `time` использовать в качестве идентификатора

2023-12-09 12:06 UTC, a1k0u commented on schemas/All.sql
> +    TIMESTAMP TIMESTAMP NOT NULL
давай везде это подправим, где есть время

2023-12-09 12:08 UTC, koufesser commented on schemas/All.sql
> +CREATE TABLE "User" (
User - зарезервированное слово в postgresql

2023-12-09 12:12 UTC, koufesser commented on schemas/All.sql
> +    SHOP_ID SERIAL PRIMARY KEY,
окей, тогда нужно исправить названия в физической модели

2023-12-09 12:14 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID SERIAL PRIMARY KEY,
да, в физическую модель нужно будет внести много изменений)

2023-12-09 12:15 UTC, a1k0u commented on schemas/All.sql
> +CREATE TABLE "User" (
давай customer тогда

2023-12-09 12:17 UTC, a1k0u commented on schemas/Item_Receipt.sql
> +    PRIMARY KEY (PRODUCT_ID, RECEIPT_ID)
тут всё ок, но объяснить пока не могу

2023-12-09 12:17 UTC, a1k0u commented on schemas/Owner.sql
> +    EMAIL VARCHAR(255) NOT NULL
а разве есть какие-то инструменты, кроме триггеров или ещё чего-то, чтобы такое изобрести?

2023-12-09 12:18 UTC, a1k0u commented on schemas/Reward.sql
> +    PRICE INTEGER NOT NULL,
Сделай один большой CHECK как в документации
`CHECK (discounted_price > 0 AND price > discounted_price)`

https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS

2023-12-09 12:19 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
ON DELETE SET NULL

2023-12-09 12:20 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
тут разве FOREIGN KEY не нужен?

2023-12-09 12:21 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
![image](https://github.com/vvvkkkggg/chashka-db/assets/88557718/e60f5f56-bfe6-48f6-a676-4eec8eb94819)
https://www.youtube.com/watch?v=vANfY96ccOY

2023-12-09 12:22 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
ON DELETE SET NULL

2023-12-09 12:22 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
ON DELETE SET NULL

2023-12-09 12:22 UTC, a1k0u commented on schemas/All.sql
> +    USER_ID INTEGER REFERENCES "User"(USER_ID),
ON DELETE CASCADE

2023-12-09 12:23 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
ON DELETE SET NULL

2023-12-09 12:23 UTC, a1k0u commented on schemas/All.sql
> +    USER_ID INTEGER REFERENCES "User"(USER_ID),
ON DELETE CASCADE

2023-12-09 12:23 UTC, a1k0u commented on schemas/All.sql
> +    USER_ID INTEGER REFERENCES "User"(USER_ID),
customer_reward

2023-12-09 12:23 UTC, a1k0u commented on schemas/All.sql
> +    REWARD_ID INTEGER REFERENCES Reward(REWARD_ID),
ON DELETE CASCADE

2023-12-09 12:24 UTC, a1k0u commented on schemas/All.sql
> +    RECEIPT_ID INTEGER REFERENCES Receipt(RECEIPT_ID),
ON DELETE CASCADE

2023-12-09 12:24 UTC, a1k0u commented on schemas/All.sql
> +    PRODUCT_ID INTEGER REFERENCES Item(PRODUCT_ID),
ON DELETE SET NULL

2023-12-09 12:24 UTC, a1k0u commented on schemas/All.sql
> +    OWNER_ID INTEGER REFERENCES Owner(OWNER_ID),
ON DELETE CASACDE

2023-12-09 12:24 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
ON DELETE CASCADE

2023-12-09 12:25 UTC, a1k0u commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
ON DELETE SET NULL

2023-12-09 12:25 UTC, a1k0u commented on schemas/All.sql
> +    USER_ID INTEGER REFERENCES "User"(USER_ID),
ON DELETE CASCADE

2023-12-09 12:26 UTC, a1k0u commented on schemas/All.sql
> +    PRODUCT_ID INTEGER REFERENCES Item(PRODUCT_ID),
гоу receipt_item

2023-12-09 12:43 UTC, koufesser commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
Почему не ON DELETE CASCADE?
Зачем нам связь User и нулевой кофейни?

2023-12-09 12:51 UTC, koufesser commented on schemas/All.sql
> +    TIMESTAMP TIMESTAMP NOT NULL
*PostgreSQL "timestamp" не является ключевым словом, и его можно использовать как имя столбца без проблем*
Думаю, можно оставить так

2023-12-09 12:54 UTC, koufesser commented on schemas/All.sql
> +    USER_ID INTEGER REFERENCES "User"(USER_ID),
Почему каскад? Нам не может понадобиться чек, если пользователь удален?

2023-12-09 13:01 UTC, koufesser commented on schemas/User_Reward.sql
> +    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
аналогично

*в PostgreSQL "timestamp" не является ключевым словом, и его можно использовать как имя столбца без проблем*
Думаю, можно оставить так

2023-12-09 13:05 UTC, koufesser commented on schemas/Reward.sql
> +    PRICE INTEGER NOT NULL,
Что такое discounted_price в контексте нашей бд

2023-12-09 13:06 UTC, koufesser commented on schemas/Item_Receipt.sql
> +    PRIMARY KEY (PRODUCT_ID, RECEIPT_ID)
Тут решайте сами, но, наверно, раз продукт у нас несколько раз может быть в чеке и количество не указано, то можно убрать

2023-12-09 13:16 UTC, koufesser commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
Как я понял, в postgres можно не писать foreign key
![image](https://github.com/vvvkkkggg/chashka-db/assets/71649059/b5062eba-68b8-417a-842f-f66998ff5baf)

2023-12-09 13:16 UTC, koufesser commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
https://www.postgresql.org/docs/current/tutorial-fk.html

2023-12-09 13:24 UTC, unicoooorn commented on schemas/Reward.sql
> +    PRICE INTEGER NOT NULL,
это просто пример из документации, в контексте нашей бд будет просто CHECK (price > 0)
не понял где Алексей предлагает один большой чек сделать)

2023-12-09 13:26 UTC, unicoooorn commented on schemas/Item_Receipt.sql
> +    PRIMARY KEY (PRODUCT_ID, RECEIPT_ID)
кстати да, тут ты прав
надо в эту таблицу count добавить, иначе мы просто не сможешь обрабатывать несколько одинаковых товаров в чеке
а зачем здесь вообще Primary Key то? можно и без него

2023-12-09 13:27 UTC, unicoooorn commented on schemas/Owner.sql
> +    EMAIL VARCHAR(255) NOT NULL
о да детка
https://stackoverflow.com/questions/5689718/how-can-i-create-a-constraint-to-check-if-an-email-is-valid-in-postgres

2023-12-09 13:28 UTC, unicoooorn commented on schemas/All.sql
> +    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
федор прав

2023-12-09 13:29 UTC, unicoooorn commented on schemas/All.sql
> +    USER_ID INTEGER REFERENCES "User"(USER_ID),
федор прав

2023-12-09 13:29 UTC, koufesser commented on schemas/Item_Receipt.sql
> +    PRIMARY KEY (PRODUCT_ID, RECEIPT_ID)
ну я пока просто убрал

2023-12-09 13:30 UTC, unicoooorn commented on schema.sql
> +    inn VARCHAR(10) UNIQUE NOT NULL,
инн у нас уникальный сам по себе, но несколько кофеен могут быть под одним inn, поэтому не unique
а еще у одного заведения может быть больше одной ккт, но я даже хз, надо ли это учитывать) не могу вспомнить кофеен с более чем одной ккт

2023-12-09 13:30 UTC, unicoooorn commented on schema.sql
> +    inn VARCHAR(10) UNIQUE NOT NULL,
давай забьем на последнее

2023-12-09 13:32 UTC, unicoooorn commented on schema.sql
> +    shop_id INTEGER REFERENCES chashka.coffeeshop(shop_id) ON DELETE SET NULL,
здесь cascade, зачем иметь товар без кофейни? другая кофейня не может его переиспользовать

2023-12-09 13:32 UTC, unicoooorn commented on schema.sql
> +    shop_id INTEGER REFERENCES chashka.coffeeshop(shop_id) ON DELETE SET NULL,
здесь тоже cascade, награды связаны с конкретными кофейнями

2023-12-10 09:37 UTC, unicoooorn approved these changes
прув

2023-12-10 09:39 UTC, merged